ckpt: 'log_Mountain/ckpt_000151.pth' #! 测试的路径 修改
seed: 7
exp_name: 'hercules'  #! 修改 #['Library', 'Mountain', 'Sports']
exp_dir: 'log_Mountain'
sampling_timesteps: 10

train:
    dataset: 'Hercules' #! 修改
    sequence: 'Mountain'
    dataroot: '/data/drj/HeRCULES' #! 修改
    resume_ckpt_path: 'log_Mountain/ckpt_000300.pth' #! 断点续训的路径 为空表示不使用断点续训 原始是155
    batch_size: 12 #todo 
    val_batch_size: 12
    image_size: [64, 512] #todo 
    original_image_size: [64, 512] #todo
    steps: 3
    skip: 2
    restart_num: 5
    lr: 3e-4
    weight_decay: 0.01
    epochs: 151
    ckpt_interval: 2
    num_workers: 16
    eval_interval: 10   #！ 训练多少轮进行一次评估
    print_interval: 50
    persistent_workers: True
    pin_memory: True
    clip_grad: 1.0

    cudnnbenchmark: True

    warmup_sche: True

profile: False


MODEL:
    _target_: models.DiffusionLocModel

    IMAGE_FEATURE_EXTRACTOR: 
        _target_:               models.image_feature_extractor.ImageFeatureExtractor
        backbone:              "vit_small_patch16_384"
        freeze:                 False
        in_channels:            4 #todo 
        new_patch_size:         [4, 16] #! 高度和宽度 
        new_patch_stride:       [4, 16] #! 步幅和patch大小一致 表示不重叠
        conv_stem:              'ConvStem'  # 'none' or 'ConvStem'
        stem_base_channels:     64 #todo 
        D_h:                    256         # hidden dimension of the stem
        image_size:             [64, 512] #todo
        decoder:                'linear'
        pretrained_path:        "dinov2_vits14_pretrain.pth"
        reuse_pos_emb:          true
        reuse_patch_emb:        false # no patch embedding as a convolutional stem (ConvStem) is used
        n_cls:                  1

    DENOISER: 
        _target_: models.Denoiser
        TRANSFORMER:
            _target_:               models.denoiser.TransformerEncoderWrapper
            d_model:                512
            nhead:                  4
            num_encoder_layers:     8
            dim_feedforward:        1024
            dropout:                0.1
            batch_first:            True
            norm_first:             True


    DIFFUSER:
        _target_: models.GaussianDiffusion
        beta_schedule: custom


sensors:
    name: 'HercluesAeva'  #! 修改
    type: 'spherical'
    proj_h: 64 #todo  修改  这两个参数定义了点云投影图的高度和宽度
    proj_w: 512
    fov_up: 15.   #! 修改 
    fov_down: -15.  #! 修改 
    fov_left: -60 #! 修改 
    fov_right: 60 #! 修改 
    # library
    # image_mean: #! 修改  18.8469727   16.91322934  -0.14603021  -0.06095492 -58.67739057 0.       
    #     - 18.8469727
    #     - 16.91322934
    #     - -0.14603021 
    #     - -0.06095492
    #     # - -58.67739057
    #     - 0

    # image_stds: #! 修改  14.72193805 14.48945343  8.01784258  1.17805055  3.87983959  1.
    #      - 14.72193805
    #      - 14.48945343
    #      - 8.01784258
    #      - 1.17805055
    #     #  - 3.87983959
    #      - 1

    # mountain
    # mountain mean 21.699028 19.367590 0.699775 -0.032836 -59.052391
    # mountain std  16.482492 16.726042 8.886495 1.305935 4.048502
    image_mean: #todo ! 修改  21.699028 19.367590 0.699775 -0.032836 -59.052391
        - 21.699028
        - 19.367590
        - 0.699775
        - -0.032836
        # - -59.052391
        - 0
    image_stds: #todo ! 修改  16.482492 16.726042 8.886495 1.305935 4.048502
        - 16.482492
        - 16.726042
        - 8.886495
        - 1.305935
        # - 4.048502
        - 1


# Data augmentation config
augmentation:
  # flip
  p_flipx: 0.
  p_flipy: 0.5

  # translation
  p_transx: 0.5
  trans_xmin: -5
  trans_xmax: 5
  p_transy: 0.5
  trans_ymin: -3
  trans_ymax: 3
  p_transz: 0.5
  trans_zmin: -1
  trans_zmax: 0.

  # rotation
  p_rot_roll: 0.5
  rot_rollmin: -5
  rot_rollmax: 5
  p_rot_pitch: 0.5
  rot_pitchmin: -5
  rot_pitchmax: 5
  p_rot_yaw: 0.5
  rot_yawmin: -45
  rot_yawmax: 45